language: csharp
dist: trusty
mono: none
dotnet: 1.0.4
before_install:
- openssl aes-256-cbc -K $encrypted_579e61165889_key -iv $encrypted_579e61165889_iv
  -in serverless-environment-variables.yml.enc -out serverless-environment-variables.yml
  -d
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-dev
before_script:
- npm install -g serverless@1.22.0
script:
- "./build.sh --quiet verify"
branches:
  only:
  - master
  - prod
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    all_branches: true
    tags: false
env:
  global:
  - secure: sYoArk9JYM8R2f2Po0akeVOH/eVwYQxK87324eSY5QSv+lM7dZulXAUahKzWuoSfHAT6s3WNTFzBzQJFZrD+aIfhyh3wP1eNABzBJhBRkd1oAJU6CP7G5jaFN6kqwpmdHxe0RWzpTVnLhTu8ljOdkbrmqEIfYlYJXUMEgrPWvFn1UdaNBtJCLqeo8IW9x3Lu8EKyoxhkjRA6MHiQU41xBMnrH5hpOYbpsAzjIJExSEQ+MrcxkC9fginCsRfEOLDYm+9ltPLJW/q5uraO3f98pS74tKpRnHXEYsfxd+JncPDsFHf2FCIytibWHOmdP3roSCr1NkDAiNU3VGR09ZuSbrb5Resi4zROutVvzmf5HgdR/Si4F3e+FZ0qSZAY53ROVX5THbnTtn4PjKe01BHAVG22Rvn2c5RfNT6actR+FbVZdlWW1GCML8TI8NRQ+79Mubh9SUnl+xyFu8eCO2oh1VCzOtEQTGnaNPSjqQ851sEvdi7um+uvxHQSgrNM8cwYuwWwLUrKejAsCVIi7E2urekXYgVlOiL8T9e/x20V8S236K0GA2OZ8Y2oO84wUI8FEtBrkgm0B7CwUcwwZWhbMVIC1fyUcPuJ+mPIh7DquykIcGR7fSbE9p/+wTQMDMZ894MixOToYSuJwAE6oX1qh1lqIZBr4lPRSouOHIjgcj8=
  - secure: ESZkgK7W70EmvfRe9eJswdUhjL5qh/Yu5pYPRiumaIGtoZ/fxtbaWbDblyLRn6/4TkJcSaRQOEATyHuWR7njWSBHkc2UjqIuNVNyVmd3ov0pc82RvGT+Zck0p977X54E0bcDWvo4FM77lju1MD6ykCmdFba/yDr1gMWaS2pPKcqDWmlk+dAVM44zZPmnJKSwS8aK/91NVb3ByT1W03bNSTGU2s3GDve86yQbhz3nX5CGAVsQEJBxl6aORAOQnHKEDf6GJAPUu8j+GFQUqb1qKkLwadjNxgC9sfYu18J4ZVTWB6gyOF1VS8fxXKx+lMzGVV4mGJmBe0gnD545kdZ3drRrL8ntna9q8TSIkyeHGh7P7yDcViQbcZbwaCBNyXD73gEUJO22ufiHyhXXvkF9Sj5GNTmDWrwE4VYfGR7bpU7DTSvJofP+q74BP/Jlk9df2zYxn2BwPqIroq5YAtp8SpLGMPuWY5ui967OKVAvyIS09A0sscuzN2wvkl68i3gZbIKTZgwIl0mBEyAw8Vz7F3X40cikLfYPuL2MUyZXwiEv0+g668bGTn5B79gKM3TNfEEGuPZTpi2mdHzntIOd8J+g1IVkEQvd3fNAWEwrBrkf++06JLnp+idpJjwBveIwWBs4FHU4PjAAoC3Dt0hkLDonw2o4y2B6lDhF0YwYEqk=
  - secure: Rx2PMJhfOwZVMgSrbA74YDLi91M7/5wIDuYkU9zxt70o/+m8DMbXYwPOGIa6ToEDXcyW0g4UqBPp+mhj/3b5i4DYrW7mlzrNxp9BLnqbroeRD5GIyz0kDHEbb22cJn5nW2gEHoE+wVjxWpTL6AsDq9p2pG7nNKJHrdRWn46PKNA2PwVHkS1XHhEj9LMgbcH7+xeDGwXBww/N+5NqUbfvL2i9dBDf5s+TUz9m9b87X0UULD7q264MoKOOAQFbDqjNHRlWjlCQKYZ0bn9zshPinl4p2Fr5/T92F4aS/wvkDzUxdN85xPRhVRwA6hbMtkzMrxuVmL1JWESytyai3X3aEe+x9Rii61bs0k/SymWc1HlEOdm56etJ09C+4x12UcL08jgkj8wpEVAsWo2WioavImSwQLiEp3qQWM+4cTtcNFmywDjSV4P1mZZsXbVcQuPpnqMJbQ1xovHijhLkb3UfJDBRDLSxicl6QUPipsAqo3d36fUR0Co1gNviODY75t41DQcSpBfT1iibVx6OPfVSTqtkC3VbFEm7KoaVbYUx9VsCaT1/WgJLNmSE4jxlKjqA/2YUU5xaqSjqYRYG4Gd+tfwCcipYVW+ULlEo2KK9nx7YtB0HTQ9xCNxp2a+DblR1QWOGFvHtZFivJXwlLMLKLsd+rhxjS1CmU0Fs5Rw/wok=
  - secure: L+cjJ8r0LPY5K3OlCbL+D/SahpUn7mj196C/ljMU0ZK9kr1iRATUamRdAOCDhDYfhIIig8sep5WEZ0ZIUlVTXIXFRrrE+uDTYvrCunAu5asnbvV5jqfgASDl0BzzCYWGlKTF55To44EXaoPgohManjDFb6kNIgHxJ02LgDBPetYamB7mct8kud9rvfRP6kjpQUTG80yyJoOn9NG/c+KstTWThB3QQqZXGk0wIARwj2yLva/PacxK7UcWTicFqz8iqsk3bhgymg46HD4+LULBw7DwL7IzW3hjZZ4+VxGyCIBM6wYxElPLMF+acsOzI3gONtP3TF74zf6iqEm/bXyGIuTYDny9H8VOo2e4NrvhzZDb8NBoH6mN2FJ59efxirShZxXLkvtvZNtvukd4VK38KhSK5BEXLB87x4l0KnNVrzHPlMUnhYQbOIsxNXEsxtOMiaGB6jGKLmFtOx4jjRoSAOF7Zb3/FjfmfOuAjrRqdcLeeS5PSICNGistqWFTr94OxNCAw9F9wlnhZqhkrsRimIfUojWY63rTi/7L0UAeWvthTxssabzVorYIXew1bFtylb4YvolDLOc9up1000ZQk/ykeBECE7Wmw+/4v/JpZZBobPNBBti6yxNu9SDYKHV33LcXNFEZ+qKyEGObbK3iGAjWIcjD/mdDlQ0+nVH4AWk=
