language: csharp
dist: trusty
mono: none
dotnet: 1.0.4
before_install:
- openssl aes-256-cbc -K $encrypted_579e61165889_key -iv $encrypted_579e61165889_iv
  -in serverless-environment-variables.yml.enc -out serverless-environment-variables.yml
  -d
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-dev
before_script:
- npm install -g serverless@1.22.0
script:
- "./build.sh --quiet verify"
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: sYoArk9JYM8R2f2Po0akeVOH/eVwYQxK87324eSY5QSv+lM7dZulXAUahKzWuoSfHAT6s3WNTFzBzQJFZrD+aIfhyh3wP1eNABzBJhBRkd1oAJU6CP7G5jaFN6kqwpmdHxe0RWzpTVnLhTu8ljOdkbrmqEIfYlYJXUMEgrPWvFn1UdaNBtJCLqeo8IW9x3Lu8EKyoxhkjRA6MHiQU41xBMnrH5hpOYbpsAzjIJExSEQ+MrcxkC9fginCsRfEOLDYm+9ltPLJW/q5uraO3f98pS74tKpRnHXEYsfxd+JncPDsFHf2FCIytibWHOmdP3roSCr1NkDAiNU3VGR09ZuSbrb5Resi4zROutVvzmf5HgdR/Si4F3e+FZ0qSZAY53ROVX5THbnTtn4PjKe01BHAVG22Rvn2c5RfNT6actR+FbVZdlWW1GCML8TI8NRQ+79Mubh9SUnl+xyFu8eCO2oh1VCzOtEQTGnaNPSjqQ851sEvdi7um+uvxHQSgrNM8cwYuwWwLUrKejAsCVIi7E2urekXYgVlOiL8T9e/x20V8S236K0GA2OZ8Y2oO84wUI8FEtBrkgm0B7CwUcwwZWhbMVIC1fyUcPuJ+mPIh7DquykIcGR7fSbE9p/+wTQMDMZ894MixOToYSuJwAE6oX1qh1lqIZBr4lPRSouOHIjgcj8=
  - secure: ESZkgK7W70EmvfRe9eJswdUhjL5qh/Yu5pYPRiumaIGtoZ/fxtbaWbDblyLRn6/4TkJcSaRQOEATyHuWR7njWSBHkc2UjqIuNVNyVmd3ov0pc82RvGT+Zck0p977X54E0bcDWvo4FM77lju1MD6ykCmdFba/yDr1gMWaS2pPKcqDWmlk+dAVM44zZPmnJKSwS8aK/91NVb3ByT1W03bNSTGU2s3GDve86yQbhz3nX5CGAVsQEJBxl6aORAOQnHKEDf6GJAPUu8j+GFQUqb1qKkLwadjNxgC9sfYu18J4ZVTWB6gyOF1VS8fxXKx+lMzGVV4mGJmBe0gnD545kdZ3drRrL8ntna9q8TSIkyeHGh7P7yDcViQbcZbwaCBNyXD73gEUJO22ufiHyhXXvkF9Sj5GNTmDWrwE4VYfGR7bpU7DTSvJofP+q74BP/Jlk9df2zYxn2BwPqIroq5YAtp8SpLGMPuWY5ui967OKVAvyIS09A0sscuzN2wvkl68i3gZbIKTZgwIl0mBEyAw8Vz7F3X40cikLfYPuL2MUyZXwiEv0+g668bGTn5B79gKM3TNfEEGuPZTpi2mdHzntIOd8J+g1IVkEQvd3fNAWEwrBrkf++06JLnp+idpJjwBveIwWBs4FHU4PjAAoC3Dt0hkLDonw2o4y2B6lDhF0YwYEqk=
