service: BusinessEvents-SubscriptionEngine 

provider:
  name: aws
  runtime: dotnetcore1.0
  stage: v1
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

package:
  artifact: src/BusinessEvents.SubscriptionEngine.Handlers/bin/release/netcoreapp1.0/publish/deploy-package.zip

functions:
  handle:
    handler: BusinessEvents.SubscriptionEngine.Handlers::BusinessEvents.SubscriptionEngine.Handlers.Handler::Handle
    events:
      - sns: BusinessEvents
  healthcheck:
    handler: BusinessEvents.SubscriptionEngine.Handlers::BusinessEvents.SubscriptionEngine.Handlers.Handler::HealthCheck
    events:
      - http:
          path: healthcheck
          method: get
          cors: true  